# Generated by Django 5.2.6 on 2025-09-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_chaicertificate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaicertificate',
            name='name',
        ),
        migrations.AlterField(
            model_name='store',
            name='chai_varieties',
            field=models.ManyToManyField(related_name='stores', to='chai.chaivariety'),
        ),
    ]
